### ISSUE TITLE
Requests don't seem to have a timeout configured

### ISSUE THREAD

**Issue by lalvarezguillen** [python-monero/monero-python#18]
I don't think the `requests` calls have a timeout configured. We should use a sane timeout. Maybe make it configurable as well

**Comment by bitmario** [comment]
Seems like there is no timeout indeed ([daemon](https://github.com/python-monero/monero-python/blob/2b981f870f9b134ffff60f55a46a728e885420ce/monero/backends/jsonrpc.py#L86), [wallet](https://github.com/python-monero/monero-python/blob/2b981f870f9b134ffff60f55a46a728e885420ce/monero/backends/jsonrpc.py#L404)).

It's definitely useful and I agree it should be configurable. However, I think we should maintain backwards compatibility and not time out by default, but only when the user specifies it when creating a `JSONRPCDaemon`/`JSONRPCWallet` object.

I think we should also add a warning stating that a timeout doesn't mean that the requested operation did not/will not succeed, since users could overlook this in dangerous cases (e.g. retrying a timed out transfer without additional checks).

**Comment by lalvarezguillen** [comment]
good points

**Comment by lalvarezguillen** [comment]
I guess we can close this now
